(function(){'use strict';document.documentElement.classList.toggle('desktop-host',!!window.launcherHost);
  if(window.launcherHost)document.documentElement.classList.add('desktop-host');var root=document.getElementById('launcher'), svg=document.getElementById('radial'), core=document.getElementById('core'), crumbs=document.getElementById('crumbs'), context=document.getElementById('context');
  var host=window.launcherHost||{}, reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  var fallback={id:'root',label:'ProjectHub',description:'A mechanical context tree for your work.',icon:'✦',children:[
    {id:'development',label:'Development',description:'Build, run, and inspect your projects.',icon:'⌘',children:[{id:'terminal',label:'Terminal',description:'Open a shell in the selected project root.',icon:'〉_',children:[]},{id:'editor',label:'VS Code',description:'Open the workspace in your editor.',icon:'▣',children:[]},{id:'git',label:'Git',description:'Inspect branches, commits, and changes.',icon:'⑂',children:[]},{id:'docs',label:'Docs',description:'Read the project notes and runbooks.',icon:'▤',children:[]}]},
    {id:'capture',label:'Capture',description:'Turn a spark into something actionable.',icon:'◉',children:[{id:'idea',label:'Idea',description:'Capture a new idea before it escapes.',icon:'✧',children:[]},{id:'task',label:'Task',description:'Create a focused next action.',icon:'✓',children:[]}]},
    {id:'knowledge',label:'Knowledge',description:'Your durable project memory.',icon:'◈',children:[{id:'roadmap',label:'Roadmap',description:'See what is coming next.',icon:'▦',children:[]},{id:'decisions',label:'Decisions',description:'Review the reasoning behind changes.',icon:'◇',children:[]}]},
    {id:'tools',label:'Tools',description:'Small utilities for daily flow.',icon:'⚒',children:[{id:'browser',label:'Browser',description:'Open a research browser window.',icon:'◌',children:[]},{id:'utilities',label:'Utilities',description:'Useful project utilities.',icon:'⚙',children:[]}]},
    {id:'ai',label:'AI',description:'Assistants and focused workflows.',icon:'✣',children:[{id:'chat',label:'Chat',description:'Start a contextual conversation.',icon:'✦',children:[]},{id:'agents',label:'Agents',description:'Run a bounded helper workflow.',icon:'♙',children:[]}]}
  ]};
  function fallbackController(data){var node=data||fallback,path=[node],selected=null,opened=false;function level(){var p=path[path.length-1];return {parentId:p.id,children:p.children||[],selectedId:selected}}function snap(){var c=path[path.length-1];return {isOpen:opened,path:path.map(function(n){return n.id}),current:c,levels:[level()],leaf:c.children&&c.children.length?null:c}}return {getState:snap,open:function(){path=[node];selected=null;opened=true;return snap()},collapse:function(){path=[node];selected=null;opened=false;return snap()},select:function(id){var p=path[path.length-1],n=(p.children||[]).filter(function(x){return x.id===id})[0];if(n){selected=id;path.push(n)}return snap()},back:function(){if(path.length>1)path.pop();else {selected=null;opened=false}return snap()},reset:function(){path=[node];selected=null;opened=false;return snap()}}}
  var supplied=(window.LauncherData&& (window.LauncherData.root||window.LauncherData.MOCK_ROOT))||window.LauncherData||fallback;
  var controller=window.LauncherTree&&window.LauncherTree.createController?window.LauncherTree.createController(supplied):fallbackController(supplied),state=controller.getState();
  function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function polar(cx,cy,r,a){var t=(a-90)*Math.PI/180;return [cx+r*Math.cos(t),cy+r*Math.sin(t)]}
  function wedgePath(cx,cy,r1,r2,a1,a2){var p1=polar(cx,cy,r1,a1),p2=polar(cx,cy,r1,a2),p3=polar(cx,cy,r2,a2),p4=polar(cx,cy,r2,a1),large=(a2-a1)>180?1:0;return 'M'+p1[0]+' '+p1[1]+' A'+r1+' '+r1+' 0 '+large+' 1 '+p2[0]+' '+p2[1]+' L'+p3[0]+' '+p3[1]+' A'+r2+' '+r2+' 0 '+large+' 0 '+p4[0]+' '+p4[1]+' Z'}
  function nodeFor(id){var found=null;function walk(n){if(!n||found)return;if(n.id===id){found=n;return}(n.children||[]).forEach(walk)}walk(supplied);return found}
  var lastMode=null;function notify(){var mode=state.isOpen?'expanded':'dormant';if(mode!==lastMode&&host.setMode){host.setMode(mode);lastMode=mode}if(host.setPointerInteractive)host.setPointerInteractive(!!state.isOpen)}
  function render(){state=controller.getState();root.classList.toggle('dormant',!state.isOpen);root.classList.toggle('deep',state.path.length>1);var qb=document.querySelector('.bridge-quit');if(qb)qb.style.display=state.isOpen?'':'none';document.getElementById('status-text').textContent=state.isOpen?'EXPANDED':'DORMANT';var cur=state.current||fallback;document.getElementById('core-label').textContent=(cur.label||'ProjectHub').toUpperCase();document.getElementById('core-hint').textContent=state.path.length>1?'BACK':'SUMMON';
    var levels=state.levels||[], active=levels[levels.length-1]||{children:cur.children||[]};var children=active.children||cur.children||[];var defs='<defs><linearGradient id="steelGrad" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#9ba6a8"/><stop offset=".46" stop-color="#566167"/><stop offset="1" stop-color="#303b40"/></linearGradient><linearGradient id="amberGrad" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#ffd083"/><stop offset=".35" stop-color="#9e672f"/><stop offset="1" stop-color="#3f2a1a"/></linearGradient></defs>';
    var out=defs, max=Math.min(children.length,10), gap=4, span=360/max-gap, r1=state.path.length>2?255:220,r2=state.path.length>2?348:330;children.slice(0,max).forEach(function(n,i){var a1=i* (360/max)+gap/2-180,a2=(i+1)*(360/max)-gap/2-180,mid=(a1+a2)/2,pt=polar(380,380,(r1+r2)/2,mid);out+='<g class="wedge '+(active.selectedId===n.id?'selected':'')+'" tabindex="0" role="button" aria-label="'+esc(n.label)+'" data-node-id="'+esc(n.id)+'"><path d="'+wedgePath(380,380,r1,r2,a1,a2)+'"></path><text class="glyph" x="'+pt[0]+'" y="'+(pt[1]-3)+'">'+esc(({code:'⌘',hub:'✦',terminal:'〉_',docs:'▤'}[n.icon]||n.icon||'◈'))+'</text><text x="'+pt[0]+'" y="'+(pt[1]+24)+'">'+esc(n.label)+'</text></g>'});svg.innerHTML=out;
    svg.querySelectorAll('.wedge').forEach(function(el){el.addEventListener('click',function(){controller.select(el.dataset.nodeId);render()});el.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();controller.select(el.dataset.nodeId);render()}});el.addEventListener('mouseenter',function(){var n=nodeFor(el.dataset.nodeId)||{};showContext(n)});});
    if(state.isOpen)showContext(cur);else context.hidden=true;core.setAttribute('aria-label',state.isOpen?'Back to previous level':'Summon ProjectHub');core.setAttribute('data-node-id','core');crumbs.innerHTML=state.path.map(function(id,i){var n=nodeFor(id)||((state.current&&id===state.current.id)?state.current:null)||{label:id};return '<button class="crumb '+(i===state.path.length-1?'active':'')+'" data-depth="'+i+'">'+esc(n.label.toUpperCase())+'</button>'+(i<state.path.length-1?'<span class="sep">/</span>':'')}).join('');crumbs.querySelectorAll('.crumb').forEach(function(b){b.addEventListener('click',function(){var d=+b.dataset.depth;while(state.path.length>d+1){state=controller.back()}render()})});notify();}
  function showContext(n){if(!n||!state.isOpen)return;context.hidden=false;document.getElementById('context-label').textContent=(n.label||'').toUpperCase();document.getElementById('context-icon').textContent=n.icon||'⌁';document.getElementById('context-description').textContent=(n.description||'')+(n.children&&n.children.length?'':'  MOCK ACTION — no command executed.')}
  core.addEventListener('click',function(){if(!state.isOpen){controller.open()}else{controller.back()}render()});document.getElementById('demo-open').addEventListener('click',function(){controller.open();render()});
  document.addEventListener('keydown',function(e){if((e.ctrlKey&&e.code==='Space')||e.key==='F2'){e.preventDefault();controller.open();render()}else if(e.key==='Escape'){e.preventDefault();if(state.isOpen){controller.back();render()}}else if(e.key==='ArrowLeft'||e.key==='Backspace'){if(state.isOpen){controller.back();render()}}else if((e.key==='ArrowRight'||e.key==='ArrowDown'||e.key==='ArrowUp')&&state.isOpen){var ws=[].slice.call(svg.querySelectorAll('.wedge'));if(ws.length){e.preventDefault();var ix=ws.indexOf(document.activeElement);ix=(ix+(e.key==='ArrowUp'||e.key==='ArrowLeft'?-1:1)+ws.length)%ws.length;ws[ix].focus();showContext(nodeFor(ws[ix].dataset.nodeId))}}});
  if(host.onSummon)host.onSummon(function(){controller.open();render()});if(host.ready)host.ready();render();
  if(host.quit){var q=document.createElement('button');q.type='button';q.className='bridge-quit';q.textContent='QUIT';q.title='Close launcher';q.style.display=state.isOpen?'':'none';q.addEventListener('click',function(){host.quit()});document.body.appendChild(q)}
  document.addEventListener('pointermove',function(e){if(!host.setPointerInteractive)return;var t=e.target,interactive=!!(t.closest&&t.closest('.wedge,.core,.crumb,.context,.bridge-quit,.demo-open'));host.setPointerInteractive(interactive)});
})();




